name: PR Preview

on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - closed

jobs:
  deploy:
    uses: Emilvorre/trainyard/.github/workflows/deploy.yml@main
    with:
      config-file: .github/pr-preview.yml
    secrets:
      kubeconfig: ${{ secrets.KUBECONFIG }}

  teardown:
    uses: Emilvorre/trainyard/.github/workflows/teardown.yml@main
    with:
      config-file: .github/pr-preview.yml
    secrets:
      kubeconfig: ${{ secrets.KUBECONFIG }}
